---
apiVersion: v1
kind: Namespace
metadata:
  name: ng
---
apiVersion: cert-manager.io/v1
kind: Issuer  # Added for cert-manager
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # replace with correct email address
    email: xxxxxxx@gmail.com 
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ng
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/issuer: "letsencrypt-prod" # Added for cert-manager
spec:
  defaultBackend:
    service:
      name: node-service
      port:
        number: 80
  tls:
  - hosts:
      - example.domain.com # Replace with correct domain name
    secretName: node-service-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: ng
  name: node-service
  labels:
    app: node
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30080
  selector:
    app: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ng
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: roxnz/node-web-app:latest
          ports:
          - containerPort: 3000
